---

name: Checks

on:
  pull-request:
    branches: ["main","develop"]
  push:
    branches: ["main","develop"]

jobs:
  linter:
  name: Code Formatting
  runs-on: ubuntu-22.04
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  automated-tests:
    name: code-testing
    runs-on: ubuntu-latest
    steps:
        - name: Check-out code Repository
          uses: actions/checkout@v3

        - name: Build the Docker image
          run:  docker compose -f docker-compose-dev.yml build

        - name: Run the Tests
          run:  docker compose -f docker-compose-dev.yml run --rm django pytest

        - name: Stop the Docker containers and remove them
          run:  docker compose -f docker-compose-dev.yml down
